apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --loglevel=warn
    target:
      group: apps
      kind: Deployment
      name: workflow-controller
      version: v1

patchesJson6902:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args
        value:
        - server
        -  --auth-mode=server
        -  --namespaced
        -  --loglevel=warn
        -  --insecure-skip-verify
    target:
      group: apps
      kind: Deployment
      name: argo-server
      version: v1

resources:
  - github.com/argoproj/argo-workflows/manifests/namespace-install?ref=v3.5.5
