# GitHub Actions Workflow
name: CI

on:
  push:
    branches:
      - main
      - improvements
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Kustomize
      uses: imranismail/setup-kustomize@v2

    - name: Validate YAML
      run: kubeval ./path/to/yaml/files/*.yaml

    - name: Lint YAML files
      run: yamllint ./path/to/yaml/files

    - name: Test Deployment
      run: argocd app sync <your-app-name>
